/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Comida;
import Entidades.Dieta;
import Entidades.MenuDiario;
import Entidades.RenglonDeMenu;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import persistencia.*;

/**
 *
 * @author Matias
 */
public class VistaCargarMenuDiario extends javax.swing.JInternalFrame {

    Conexion conexion = new Conexion("jdbc:mysql://localhost/nutricionista", "root", "");
    DietaData dietaData = new DietaData(conexion);
    RenglonDeMenuData renglonData = new RenglonDeMenuData(conexion);
    ComidaData comidaData = new ComidaData(conexion);
    MenuDiarioData menuData = new MenuDiarioData(conexion);
    public VistaCargarMenuDiario() {
        initComponents();
        cargarCombo(dietasAuto);
        cargarCombo(dietasManu);
        btnGenerarManu.setEnabled(false);
        brnGenerarAuto.setEnabled(false);
        estadoManu.setEnabled(false);
        ingredientes.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dietasManu = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        estadoManu = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        ingredientes = new javax.swing.JTextField();
        btnGenerarManu = new javax.swing.JButton();
        brnGenerarAuto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dietasAuto = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 30)); // NOI18N
        jLabel1.setText("Generar Menu Diario");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setText("MANUAL");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("AUTOMATICO");

        dietasManu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dietasManuItemStateChanged(evt);
            }
        });

        jLabel5.setText("DIETA");

        estadoManu.setText("ESTADO");
        estadoManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoManuActionPerformed(evt);
            }
        });

        jLabel6.setText("INGREDIENTES");

        btnGenerarManu.setText("GENERAR");
        btnGenerarManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarManuActionPerformed(evt);
            }
        });

        brnGenerarAuto.setText("GENERAR");
        brnGenerarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnGenerarAutoActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel8.setText("DIETA");

        dietasAuto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dietasAutoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(58, 58, 58)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brnGenerarAuto)
                            .addComponent(btnGenerarManu)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estadoManu)
                                    .addComponent(dietasManu, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dietasAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnSalir))
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dietasManu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(estadoManu)
                .addGap(18, 18, 18)
                .addComponent(btnGenerarManu)
                .addGap(40, 40, 40)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dietasAuto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ingredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(brnGenerarAuto)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estadoManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoManuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoManuActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGenerarManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarManuActionPerformed
        Dieta dieta = new Dieta();
        boolean estado = estadoManu.isSelected();
        
        MenuDiario menu = new MenuDiario();
        int indice = dietasManu.getSelectedIndex();
            int contador = 0;
            for (Dieta a : dietaData.listaDietaConPacienteCargados()) {
                contador++;
                if (contador == indice) {
                    menu.setDieta(a);
                    break;
                }
            }
        int dias = menu.getDieta().cantDias();
        menu.setEstado(estado);
        for (int i = 0; i < dias; i++) {
            menu.setDia(i+1);
            menuData.GenerarMenuDiario(menu);
        }
            dietasAuto.setSelectedIndex(0);
            dietasManu.setSelectedIndex(0);
            this.ingredientes.setText("");
            estadoManu.setSelected(false);
    }//GEN-LAST:event_btnGenerarManuActionPerformed

    private void brnGenerarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnGenerarAutoActionPerformed

        if (comprobacion()) {  // Ejecutar solo si comprobación pasa
            ArrayList<Comida> alimentos = new ArrayList<>(comidaData.listarComidas());
            Dieta dietaSeleccionada = dietaData.listaDietaConPacienteCargados().get(dietasAuto.getSelectedIndex() - 1);
            int calorias = 0;

            MenuDiario menuCargado = new MenuDiario();
            menuCargado.setDieta(dietaSeleccionada);
            menuCargado.setEstado(true);

            int dias = dietaSeleccionada.cantDias();
            String textoIngredientes = ingredientes.getText();
            List<String> listaIngredientes = Arrays.asList(textoIngredientes.split("\\s*,\\s*"));

            for (int i = 0; i < dias; i++) {
                MenuDiario menuGenerado = MenuDiario.generarDietaDiaria(alimentos, listaIngredientes, i + 1);
                menuCargado.setDia(i + 1);

                menuData.GenerarMenuDiarioAuto(menuCargado);

                for (RenglonDeMenu comida : menuGenerado.getComidas()) {
                    comida.setMenu(menuCargado);
                    calorias += comida.getSubtotalCalorias();
                    renglonData.guardarRenglonDeMenu(comida);
                }
            }

            dietaSeleccionada.setTotalCalorias(calorias);
            dietaData.alterarDieta(dietaSeleccionada);

            dietasAuto.setSelectedIndex(0);
            dietasManu.setSelectedIndex(0);
            this.ingredientes.setText("");
            estadoManu.setSelected(false);
        }

        
    }//GEN-LAST:event_brnGenerarAutoActionPerformed

    private void dietasManuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dietasManuItemStateChanged
        if(dietasManu.getSelectedIndex() == 0){
            btnGenerarManu.setEnabled(false);
            estadoManu.setEnabled(false);
        } else {
            btnGenerarManu.setEnabled(true);
            estadoManu.setEnabled(true);
            brnGenerarAuto.setEnabled(false);
            ingredientes.setEnabled(false);
            dietasAuto.setSelectedIndex(0);
        }
    }//GEN-LAST:event_dietasManuItemStateChanged

    private void dietasAutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dietasAutoItemStateChanged
        if(dietasAuto.getSelectedIndex() == 0){
            brnGenerarAuto.setEnabled(false);
            ingredientes.setEnabled(false);
        } else {
            brnGenerarAuto.setEnabled(true);
            ingredientes.setEnabled(true);
            btnGenerarManu.setEnabled(false);
            estadoManu.setEnabled(false);
            dietasManu.setSelectedIndex(0);
        }
    }//GEN-LAST:event_dietasAutoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnGenerarAuto;
    private javax.swing.JButton btnGenerarManu;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> dietasAuto;
    private javax.swing.JComboBox<String> dietasManu;
    private javax.swing.JCheckBox estadoManu;
    private javax.swing.JTextField ingredientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    private void cargarCombo(JComboBox<String> combo) {
        combo.addItem("- - DIETAS SIN MENU - -");
        for (Dieta a : menuData.listaDietaSinMenu()) {
            combo.addItem(a.toString());
        }
        combo.setSelectedIndex(0);
        // Usar un renderer para mostrar tooltips
        combo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (c instanceof JComponent && value != null) {
                    ((JComponent) c).setToolTipText(value.toString()); // Mostrar tooltip completo
                }
                return c;
            }
        });
    }

    private boolean comprobacion() {
        String texto = ingredientes.getText();
        List<String> ingredi = Arrays.asList(texto.split("\\s*,\\s*"));
        if (texto.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese al menos 1 ingrediente", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (ingredi.size() > 3) {
            JOptionPane.showMessageDialog(this, "Ingrese entre 1 y 3 ingredientes", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    
}
