package Vistas;

import Entidades.*;
import static java.awt.PageAttributes.MediaType.A;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.mariadb.jdbc.Connection;
import persistencia.Conexion;
import persistencia.DietaData;
import persistencia.PacienteData;


public class vistaListadePacientes extends javax.swing.JInternalFrame {
private final Conexion conexion = new Conexion("jdbc:mysql://localhost/nutricionista", "root", "");
private PacienteData pacienteData = new PacienteData(conexion);
private DietaData dietadata = new DietaData(conexion);

    public vistaListadePacientes() {
        initComponents();
        armarTabla();
        cargarlistaPaciente();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton6 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaPaciente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Actualizar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        pesologrado = new javax.swing.JRadioButton();
        seacerca = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");

        jToggleButton1.setText("jToggleButton1");

        jButton6.setText("jButton6");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Edad", "Altura", "Peso actual", "Peso buscado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaPacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaPaciente);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 690, 244));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista Paciente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 330, -1));

        Salir.setBackground(new java.awt.Color(153, 153, 153));
        Salir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(0, 0, 0));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trash (1).png"))); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Buscar Paciente:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        Id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdKeyTyped(evt);
            }
        });
        jPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, -1));

        Actualizar.setBackground(new java.awt.Color(153, 153, 153));
        Actualizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Actualizar.setForeground(new java.awt.Color(0, 0, 0));
        Actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/refresh (2).png"))); // NOI18N
        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, -1, -1));

        borrar.setBackground(new java.awt.Color(153, 153, 153));
        borrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        borrar.setForeground(new java.awt.Color(0, 0, 0));
        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/trash (1).png"))); // NOI18N
        borrar.setText("Eliminar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jPanel1.add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

        pesologrado.setBackground(new java.awt.Color(153, 153, 153));
        pesologrado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pesologrado.setForeground(new java.awt.Color(0, 0, 0));
        pesologrado.setText("Peso logrado");
        pesologrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesologradoActionPerformed(evt);
            }
        });
        jPanel1.add(pesologrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        seacerca.setBackground(new java.awt.Color(153, 153, 153));
        seacerca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        seacerca.setForeground(new java.awt.Color(0, 0, 0));
        seacerca.setText("Se acerca al peso");
        seacerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seacercaActionPerformed(evt);
            }
        });
        jPanel1.add(seacerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/d53461c1acc264746ea5bc688eac96b3.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaPacienteMouseClicked

    }//GEN-LAST:event_listaPacienteMouseClicked

//buscar
    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
         
         
    }//GEN-LAST:event_IdActionPerformed
//actualizar
    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
    for (int fila = 0; fila < listaPaciente.getRowCount(); fila++) {
    int nroPaciente = (int) listaPaciente.getValueAt(fila, 0);
    Paciente paciente = pacienteData.buscarPaciente(nroPaciente);

    if (paciente != null) {
        String nombre = listaPaciente.getValueAt(fila, 1).toString().trim();

        int edad = 0;
        double altura = 0.0;
        double pesoActual = 0.0;
        double pesoBuscado = 0.0;
        boolean datosValidos = true;

        try {
            edad = Integer.parseInt(listaPaciente.getValueAt(fila, 2).toString().trim());
        } catch (NumberFormatException e) {
            System.out.println("Error en el formato de edad en la fila " + fila);
            datosValidos = false;
        }

        try {
            String alturaStr = listaPaciente.getValueAt(fila, 3).toString().trim().replace(",", ".");
            altura = Double.parseDouble(alturaStr);
        } catch (NumberFormatException e) {
            System.out.println("Error en el formato de altura en la fila " + fila);
            datosValidos = false;
        }

        try {
            String pesoActualStr = listaPaciente.getValueAt(fila, 4).toString().trim().replace(",", ".");
            pesoActual = Double.parseDouble(pesoActualStr);
        } catch (NumberFormatException e) {
            System.out.println("Error en el formato de peso actual en la fila " + fila);
            datosValidos = false;
        }

        try {
            String pesoBuscadoStr = listaPaciente.getValueAt(fila, 5).toString().trim().replace(",", ".");
            pesoBuscado = Double.parseDouble(pesoBuscadoStr);
        } catch (NumberFormatException e) {
            System.out.println("Error en el formato de peso buscado en la fila " + fila);
            datosValidos = false;
        }

        if (datosValidos) {
            boolean actualizado = false;

            if (!paciente.getNombre().equals(nombre)) {
                paciente.setNombre(nombre);
                actualizado = true;
            }
            if (paciente.getEdad() != edad) {
                paciente.setEdad(edad);
                actualizado = true;
            }
            if (paciente.getAltura() != altura) {
                paciente.setAltura(altura);
                actualizado = true;
            }
            if (paciente.getPesoActual() != pesoActual) {
                paciente.setPesoActual(pesoActual);
                actualizado = true;
            }
            if (paciente.getPesoBuscado() != pesoBuscado) {
                paciente.setPesoBuscado(pesoBuscado);
                actualizado = true;
            }

            if (actualizado) {
                pacienteData.actualizarPaciente(paciente);
                System.out.println("Paciente actualizado: " + nroPaciente);
            }
        } else {
            System.out.println("Datos inválidos para el paciente con ID " + nroPaciente + " en la fila " + fila);
        }
    } else {
        System.out.println("Paciente con ID " + nroPaciente + " no encontrado");
    }
}

JOptionPane.showMessageDialog(this, "Actualización completada para todos los pacientes.");
borrarFilasTablas();
cargarlistaPaciente();


   
    }//GEN-LAST:event_ActualizarActionPerformed
//editar
    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
                                      
    int filaSeleccionada = listaPaciente.getSelectedRow();
    
    if (filaSeleccionada != -1) {
  
        int id = (int) listaPaciente.getValueAt(filaSeleccionada, 0);
        
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar este elemento?", "Confirmación de borrado", JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            
            pacienteData.borradoFisicoPaciente(id);
             
            borrarFilasTablas();            
            cargarlistaPaciente();

        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecciona un elemento para eliminar.");
    }
    }//GEN-LAST:event_borrarActionPerformed

    private void pesologradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesologradoActionPerformed
        Actualizar.setEnabled(false);
        borrar.setEnabled(false);
        Salir.setEnabled(false);
        seacerca.setSelected(false);
        cargarlistaPaciente();
        borrarFilasTablas();
        ArrayList<Paciente> pacientes = (ArrayList<Paciente>) Paciente.listarLosQueLLegaron(pacienteData.listaPaciente());
        for (Paciente p : pacientes) {
            int nroPaciente = p.getNroPaciente();
            String nombre = p.getNombre();
            int edad = p.getEdad();
            

            String altura = String.format("%.2f", p.getAltura());
            String pesoActual = String.format("%.2f", p.getPesoActual());
            String pesoBuscado = String.format("%.2f", p.getPesoBuscado());

            modelo.addRow(new Object[]{nroPaciente, nombre, edad, altura, pesoActual, pesoBuscado});
        }
        if (!pesologrado.isSelected()) {
            borrarFilasTablas();
            cargarlistaPaciente();
            Actualizar.setEnabled(true);
            borrar.setEnabled(true);
            Salir.setEnabled(true);
        }
        
    }//GEN-LAST:event_pesologradoActionPerformed

    private void IdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdKeyTyped
//        borrarFilasTablas();
//        if (Id.getText().equals("")) {
//            cargarlistaPaciente();
//        } else{
//             try {
//                int nroPaciente = Integer.parseInt(Id.getText());
//
//                Paciente paciente = pacienteData.buscarPaciente(nroPaciente);
//
//                if (paciente != null) {
//                    DefaultTableModel model = (DefaultTableModel) listaPaciente.getModel();
//                    model.setRowCount(0); // Limpiar filas previas
//
//                    model.addRow(new Object[]{
//                        paciente.getNroPaciente(), 
//                        paciente.getNombre(), 
//                        paciente.getEdad(), 
//                        paciente.getAltura(), 
//                        paciente.getPesoActual(), 
//                        paciente.getPesoBuscado()
//                    });
//                } else {
//                    JOptionPane.showMessageDialog(this, "No se encontró un paciente con ese ID.");
//                }
//            } catch (NumberFormatException e) {
//                JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido como ID.");
//            }
//         }
    }//GEN-LAST:event_IdKeyTyped

    private void seacercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seacercaActionPerformed
        Actualizar.setEnabled(false);
        borrar.setEnabled(false);
        Salir.setEnabled(false);
        pesologrado.setSelected(false);
        borrarFilasTablas();
        String[] columnanueva = {"Nro Paciente", "Nombre Completo","Peso Actual","Peso Buscado","¿Se acerca al peso?"};
        DefaultTableModel modelo2 = new DefaultTableModel(columnanueva, 0);
        listaPaciente.setModel(modelo2);
        ArrayList<Dieta> listaDieta = dietadata.listaDietaConPacienteCargados();
        for (Paciente paciente : pacienteData.listaPaciente()) {
            int nroPaciente = paciente.getNroPaciente();
            String nombre = paciente.getNombre();
            String pesoActual = String.format("%.2f", paciente.getPesoActual());
            String pesoBuscado = String.format("%.2f", paciente.getPesoBuscado());

            Dieta dieta = listaDieta.stream()
            .filter(d -> d.getPaciente() != null && d.getPaciente().getNroPaciente() == nroPaciente)
            .findFirst()
            .orElse(null);

            if (dieta != null) {
                if (!(paciente.getPesoActual() <= paciente.getPesoBuscado())) {
                    boolean acerca = paciente.seAcercaAlPeso(dieta);
                    modelo2.addRow(new Object[]{nroPaciente,nombre,pesoActual,pesoBuscado,acerca});
                }

            }
        }

        if (!seacerca.isSelected()) {
            borrarFilasTablas();
            cargarlistaPaciente();
            Actualizar.setEnabled(true);
            borrar.setEnabled(true);
            Salir.setEnabled(true);
        }
    }//GEN-LAST:event_seacercaActionPerformed

    private void IdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdKeyReleased
         borrarFilasTablas();
        if (Id.getText().equals("")) {
            cargarlistaPaciente();
        } else{
             try {
                int nroPaciente = Integer.parseInt(Id.getText());

                Paciente paciente = pacienteData.buscarPaciente(nroPaciente);

                if (paciente != null) {
                    DefaultTableModel model = (DefaultTableModel) listaPaciente.getModel();
                    model.setRowCount(0); // Limpiar filas previas

                    model.addRow(new Object[]{
                        paciente.getNroPaciente(), 
                        paciente.getNombre(), 
                        paciente.getEdad(), 
                        paciente.getAltura(), 
                        paciente.getPesoActual(), 
                        paciente.getPesoBuscado()
                    });
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró un paciente con ese ID.");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Por favor, ingresa un número válido como ID.");
            }
         }
    }//GEN-LAST:event_IdKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JTextField Id;
    private javax.swing.JButton Salir;
    private javax.swing.JButton borrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable listaPaciente;
    private javax.swing.JRadioButton pesologrado;
    private javax.swing.JRadioButton seacerca;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel modelo = new DefaultTableModel(){
        public boolean isCellEditable(int fila, int columna){
            return columna != 0;
        }
    };
    private void cargarlistaPaciente() { 

        for (Paciente p : pacienteData.listaPaciente()) {
            int nroPaciente = p.getNroPaciente();
            String nombre = p.getNombre();
            int edad = p.getEdad();

            String altura = String.format("%.2f", p.getAltura());
            String pesoActual = String.format("%.2f", p.getPesoActual());
            String pesoBuscado = String.format("%.2f", p.getPesoBuscado());

            modelo.addRow(new Object[]{nroPaciente, nombre, edad, altura, pesoActual, pesoBuscado});
        }

        listaPaciente.setModel(modelo);
    }
    private void armarTabla(){
        modelo.addColumn("Nro Paciente");
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("Altura (m)");
        modelo.addColumn("Peso Actual (kg)");
        modelo.addColumn("Peso Buscado (kg)");
    }
    private void borrarFilasTablas(){
        int fila= modelo.getRowCount()-1;
        for (int i = fila ; i >= 0 ; i--) {
            modelo.removeRow(i);
        }
    }
    private void borrarColum(){
        int colum = modelo.getColumnCount()-1;
        for (int i = colum; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }
}