/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Entidades.Comida;
import Entidades.Dieta;
import Entidades.MenuDiario;
import Entidades.RenglonDeMenu;
import java.awt.Component;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.JOptionPane;
import persistencia.*;

/**
 *
 * @author Matias
 */
public class VistaCargarMenuDiario extends javax.swing.JInternalFrame {

    Conexion conexion = new Conexion("jdbc:mysql://localhost/nutricionista", "root", "");
    DietaData dietaData = new DietaData(conexion);
    RenglonDeMenuData renglonData = new RenglonDeMenuData(conexion);
    ComidaData comidaData = new ComidaData(conexion);
    MenuDiarioData menuData = new MenuDiarioData(conexion);
    public VistaCargarMenuDiario() {
        initComponents();
        cargarCombo(dietasAuto);
        cargarCombo(dietasManu);
        btnGenerarManu.setEnabled(false);
        brnGenerarAuto.setEnabled(false);
        estadoManu.setEnabled(false);
        ingredientes.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dietasManu = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        estadoManu = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        ingredientes = new javax.swing.JTextField();
        btnGenerarManu = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        brnGenerarAuto = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dietasAuto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Generar Menu Diario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("MANUAL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("AUTOMATICO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        dietasManu.setBackground(new java.awt.Color(153, 153, 153));
        dietasManu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dietasManu.setForeground(new java.awt.Color(0, 0, 0));
        dietasManu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dietasManuItemStateChanged(evt);
            }
        });
        jPanel1.add(dietasManu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 300, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("DIETA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        estadoManu.setBackground(new java.awt.Color(153, 153, 153));
        estadoManu.setForeground(new java.awt.Color(204, 204, 204));
        estadoManu.setText("ESTADO");
        estadoManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoManuActionPerformed(evt);
            }
        });
        jPanel1.add(estadoManu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 80, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("INGREDIENTES:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        ingredientes.setBackground(new java.awt.Color(153, 153, 153));
        ingredientes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ingredientes.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(ingredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 140, -1));

        btnGenerarManu.setBackground(new java.awt.Color(51, 51, 51));
        btnGenerarManu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGenerarManu.setForeground(new java.awt.Color(204, 204, 204));
        btnGenerarManu.setText("GENERAR");
        btnGenerarManu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarManuActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerarManu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 100, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        brnGenerarAuto.setBackground(new java.awt.Color(51, 51, 51));
        brnGenerarAuto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        brnGenerarAuto.setForeground(new java.awt.Color(204, 204, 204));
        brnGenerarAuto.setText("GENERAR");
        brnGenerarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnGenerarAutoActionPerformed(evt);
            }
        });
        jPanel1.add(brnGenerarAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 100, 30));

        btnSalir.setBackground(new java.awt.Color(153, 153, 153));
        btnSalir.setForeground(new java.awt.Color(0, 0, 0));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exit (2).png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("DIETA:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        dietasAuto.setBackground(new java.awt.Color(153, 153, 153));
        dietasAuto.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dietasAuto.setForeground(new java.awt.Color(0, 0, 0));
        dietasAuto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dietasAutoItemStateChanged(evt);
            }
        });
        jPanel1.add(dietasAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 300, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/4994444c2a8447af58521d63b78b4b02.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -400, -1, 840));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void estadoManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoManuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoManuActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGenerarManuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarManuActionPerformed
        if (dietasManu.getSelectedIndex() <= 0) { // Verificar que se haya seleccionado una dieta válida
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una dieta válida.");
            return;
        }

        boolean estado = estadoManu.isSelected();
        Dieta dietaSeleccionada = dietasCombo.get(dietasManu.getSelectedIndex() - 1);

        MenuDiario menu = new MenuDiario();
        menu.setDieta(dietaSeleccionada);
        int dias = menu.getDieta().cantDias();
        menu.setEstado(estado);

        for (int i = 0; i < dias; i++) {
            menu.setDia(i + 1);
            menuData.GenerarMenuDiario(menu);
        }
        JOptionPane.showMessageDialog(this, "Menu generado con exito!", "CORRECTO!", JOptionPane.INFORMATION_MESSAGE);
        dietasAuto.setSelectedIndex(0);
        dietasManu.setSelectedIndex(0);
        this.ingredientes.setText("");
        estadoManu.setSelected(false);
        cargarCombo(dietasManu);
        cargarCombo(dietasAuto);
    }//GEN-LAST:event_btnGenerarManuActionPerformed

    private void brnGenerarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnGenerarAutoActionPerformed

        if (dietasAuto.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una dieta válida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (comprobacion()) {  
            ArrayList<Comida> alimentos = new ArrayList<>(comidaData.listarComidas());
            Dieta dietaSeleccionada = dietasCombo.get(dietasAuto.getSelectedIndex() - 1);
            int calorias = 0;
            

            MenuDiario menuCargado = new MenuDiario();
            menuCargado.setDieta(dietaSeleccionada);
            menuCargado.setEstado(true);

            int dias = dietaSeleccionada.cantDias();
            String textoIngredientes = ingredientes.getText();
            List<String> listaIngredientes = Arrays.asList(textoIngredientes.split("\\s*,\\s*"));

            for (int i = 0; i < dias; i++) {
                MenuDiario menuGenerado = MenuDiario.generarDietaDiaria(alimentos, listaIngredientes, i + 1);
                if (menuGenerado == null) {
                    return;
                }
                menuCargado.setDia(i + 1);

                menuData.GenerarMenuDiarioAuto(menuCargado);

                for (RenglonDeMenu comida : menuGenerado.getComidas()) {
                    comida.setMenu(menuCargado);
                    calorias += comida.getSubtotalCalorias();
                    renglonData.guardarRenglonDeMenu(comida);
                }
            }

            dietaSeleccionada.setTotalCalorias(calorias);
            dietaData.alterarDieta(dietaSeleccionada);
            JOptionPane.showMessageDialog(this, "Menu generado con exito!", "CORRECTO!", JOptionPane.INFORMATION_MESSAGE);
            dietasAuto.setSelectedIndex(0);
            dietasManu.setSelectedIndex(0);
            this.ingredientes.setText("");
            estadoManu.setSelected(false);
            cargarCombo(dietasAuto);
            cargarCombo(dietasManu);
        }

        
    }//GEN-LAST:event_brnGenerarAutoActionPerformed

    private void dietasManuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dietasManuItemStateChanged
        if(dietasManu.getSelectedIndex() == 0){
            btnGenerarManu.setEnabled(false);
            estadoManu.setEnabled(false);
        } else {
            btnGenerarManu.setEnabled(true);
            estadoManu.setEnabled(true);
            brnGenerarAuto.setEnabled(false);
            ingredientes.setEnabled(false);
            dietasAuto.setSelectedIndex(0);
        }
    }//GEN-LAST:event_dietasManuItemStateChanged

    private void dietasAutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dietasAutoItemStateChanged
        if(dietasAuto.getSelectedIndex() == 0){
            brnGenerarAuto.setEnabled(false);
            ingredientes.setEnabled(false);
        } else {
            brnGenerarAuto.setEnabled(true);
            ingredientes.setEnabled(true);
            btnGenerarManu.setEnabled(false);
            estadoManu.setEnabled(false);
            dietasManu.setSelectedIndex(0);
        }
    }//GEN-LAST:event_dietasAutoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnGenerarAuto;
    private javax.swing.JButton btnGenerarManu;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> dietasAuto;
    private javax.swing.JComboBox<String> dietasManu;
    private javax.swing.JCheckBox estadoManu;
    private javax.swing.JTextField ingredientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
    private List<Dieta> dietasCombo = new ArrayList<>();

    private void cargarCombo(JComboBox<String> combo) {
        combo.removeAllItems();
        combo.addItem("- - DIETAS SIN MENU - -");
        dietasCombo.clear(); // Asegúrate de limpiar la lista antes de llenarla nuevamente
        for (Dieta dieta : menuData.listaDietaSinMenu()) {
            dietasCombo.add(dieta); // Guarda cada dieta en la lista
            combo.addItem(dieta.toString()); // Agrega su representación al ComboBox
            }
        combo.setSelectedIndex(0);
        // Usar un renderer para mostrar tooltips
        combo.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (c instanceof JComponent && value != null) {
                    ((JComponent) c).setToolTipText(value.toString()); // Mostrar tooltip completo
                }
                return c;
            }
        });
    }

    private boolean comprobacion() {
        String texto = ingredientes.getText();
        List<String> ingredi = Arrays.asList(texto.split("\\s*,\\s*"));
        if (texto.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese al menos 1 ingrediente", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        } else if (ingredi.size() > 3) {
            JOptionPane.showMessageDialog(this, "Ingrese entre 1 y 3 ingredientes", "ERROR", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    
}
